---
- hosts: dispatcher
  
  vars:
    #http_port: 80
    #max_clients: 200
    #remote_user: root
  
  tasks:
    - name: create a shell script file for {{ vhost }}
      template: src=testTemplate.j2 dest=/etc/httpd/conf.d/{{ vhost }}
    
    - name: remotely create a folder
      shell: somescript.sh >> somelog.txt
      args:
        chdir: somedir/
        creates: somelog.txt    
      
 # roles:
 #   - common
 #   - webserver
    
  