---
- hosts: authoring
  
  vars:
    #http_port: 80
    #max_clients: 200
    #remote_user: root
  
  tasks:
    - name: test copy command
      copy: src=testTemplate.j2 dest=/home1/ccqc/testTemplate.copy
  
    - name: create a shell script file for {{ vhost }}
      template: src=testTemplate.j2 dest=/home1/ccqc/testTemplate.sh mode=0777
    
    - name: remotely execute
      shell: testTemplate.sh >> somelog.txt
      args:
        chdir: /home1/ccqc
    
      
 # roles:
 #   - common
 #   - webserver
    
  