---

- name: app root
  tags: [rails, git]
  file: path={{ app_root }} state=directory mode="0777" owner=root group=root
  when: production == true
  sudo: yes

- name: add nginx repo
  sudo: yes
  template: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: install packages
  sudo: yes
  yum: name="{{ item }}" state=latest
  with_items:
  - nginx # requires nginx repo
  notify: restart nginx # see handlers/main.yml
